export const INPUT_CHANGE = 'INPUT_CHANGE';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const NO_RESULTS_FOUND = 'NO_RESULTS_FOUND';
export const ON_RESULTS_FOUND = 'ON_RESULTS_FOUND';
export const ON_REQUEST_FAILED = 'ON_REQUEST_FAILED';
export const SELECT_CHANGE = 'SELECT_CHANGE';
export const ON_DIALOGUE_OPEN = 'ON_DIALOGUE_OPEN';
export const ON_DIALOGUE_CLOSED = 'ON_DIALOGUE_CLOSED';